import { TabWidget, ListView, HorizontalBox } from "std-widgets.slint";
import { SystemLog, SmallText, PulseDot } from "../components.slint";
import { Pod, ConnectionState } from "../data.slint";
import { Palette } from "../palette.slint";

component PodListDelegate inherits Rectangle {
    in property <Pod> pod;
    in property <bool> selected;
    callback clicked();

    background: Palette.background-card;
    border-width: 1px;
    border-color: Palette.border-subtle;
    animate background, border-color { duration: 100ms; }

    HorizontalBox {
        cross-axis-alignment: center;
        PulseDot {
            pulse: pod.connection-state == ConnectionState.connecting;
            background: pod.connection-state == ConnectionState.connected ? Palette.log-info :
                pod.connection-state == ConnectionState.connecting ? Palette.log-debug :
                Palette.log-error;
        }

        title := SmallText {
            text: pod.id;
            animate color { duration: 100ms; }
        }
    }

    touch-area := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    states [
        pressed when touch-area.pressed: {
            root.background: Palette.background-elevated.brighter(1);
            root.border-color: Palette.border;
            title.color: Palette.text-primary;
        }
        hover when touch-area.has-hover: {
            root.background: Palette.background-elevated;
        }
        selected when root.selected: {
            root.border-color: Palette.border;
        }
    ]
}

export component PodConfigTab inherits Rectangle {
    in property <[Pod]> pods: [
        { id: "Pod-Connected", connection_state: ConnectionState.connected },
        { id: "Pod-Connecting", connection_state: ConnectionState.connecting },
        { id: "Pod-Disconnected", connection_state: ConnectionState.disconnected },
    ];

    sidebar := VerticalLayout {
        x: 0;
        y: 0;
        width: 33%;

        ListView {
            for pod in pods: PodListDelegate {
                width: parent.width;
                height: 30px;
                pod: pod;
                selected: pod.connection_state == ConnectionState.connecting;
            }
        }
    }

    split := Rectangle {
        width: 1px;
        height: 100%;
        x: sidebar.width;
        y: 0;
        background: Palette.border;
    }

    content := VerticalLayout {
        x: split.x + split.width;
        y: 0;
        width: root.width - sidebar.width - split.width;
        padding: 20px;
        padding-top: 40px;
        padding-bottom: 60px;
        spacing: 15px;
        alignment: LayoutAlignment.space-between;
    }
}
