import { Pod, Dispenser } from "../data.slint";

export enum CalibrationStepStatus {
    idle,
    running,
    success,
    error,
}

export struct DispenserCalibrationState {
    offset-status: CalibrationStepStatus,
    reference-status: CalibrationStepStatus,
    pump-status: CalibrationStepStatus,
    measured-ml-per-step: string,
    error-message: string,
}

export global DispenserCalibrationContext {
    in-out property <DispenserCalibrationState> state: {
        offset-status: CalibrationStepStatus.idle,
        reference-status: CalibrationStepStatus.idle,
        pump-status: CalibrationStepStatus.idle,
        measured-ml-per-step: "",
        error-message: "",
    };

    public function update-calibration-error(error: string) {
        self.state.error-message = error;
    }

    public function update-offset-status(status: CalibrationStepStatus) {
        self.state.offset-status = status;
    }

    public function update-ref-weight-status(status: CalibrationStepStatus) {
        self.state.reference-status = status;
    }

    public function update-pump-status(status: CalibrationStepStatus) {
        self.state.pump-status = status;
    }

    public function update-pump-measured-calibrated-value(litre_str: string) {
        self.state.measured-ml-per-step = litre-str;
    }

    // implemented by business logic
    callback calibrate-offset(Pod, Dispenser);
    callback calibrate-reference(Pod, Dispenser, int /* reference-weight-g */);
    callback calibrate-pump(Pod, Dispenser, int /* steps */);

    public function reset-state() {
        state = {
            offset-status: CalibrationStepStatus.idle,
            reference-status: CalibrationStepStatus.idle,
            pump-status: CalibrationStepStatus.idle,
            measured-ml-per-step: 0,
            error-message: "",
        };
    }
}
