
export global ProcessContext {
    in-out property <string> error-title: "Pod error";
    in-out property <string> error-description: "The dispensing pod did not respond before the safety timeout elapsed.";
    in-out property <string> error-item-category: "I"; // e.g. "I" for ingredient, "D" for dispenser etc.
    in-out property <string> error-item-name: "Orangensaft"; // e.g. ingredient failed / dispenser etc.
    in-out property <string> error-item-details: "Pod 1 - Dispenser 3";

    in-out property <duration> elapsed-time: 30s;
    in-out property <int> boost: 0;

    callback process-active-recipe(int/* boost */);
}
