import { GlassDescriptor } from "../data.slint";
export global ProcessContext {
    in-out property <string> customer-title: "Kurze Unterbrechung";
    in-out property <string> customer-message: "Es gab ein technisches Problem. Bitte wende dich an das Personal.";
    in-out property <string> technical-title: "Pod-Fehler";
    in-out property <string> technical-description: "Der Pod hat innerhalb des Sicherheits-Zeitlimits nicht reagiert.";
    in-out property <string> error-item-category: "I"; // e.g. "I" for ingredient, "D" for dispenser etc.
    in-out property <string> error-item-name: "Orangensaft"; // e.g. ingredient failed / dispenser etc.
    in-out property <string> error-item-details: "Pod 1 - Dispenser 3";

    in-out property <duration> elapsed-time: 30s;
    in-out property <int> boost: 0;
    in-out property <GlassDescriptor> glass;
    in-out property <int> glass-volume;

    callback process-active-recipe();
    callback abort();
}
