import {
    LogEntry,
    Pod,
    RecipeView,
    Dispenser,
    ConnectionState,
    DispenserType,
} from "./../data.slint";
export global RecipeContext {
    in-out property <[RecipeView]> recipes;
    in-out property <RecipeView> active-recipe: {name: "Mojito", image: @image-url("../../../db/recipes/mojito.png")};
    in-out property <[string]> ingredient-ids: /* example data */ ["vodka", "orange_juice", "test2"];

    callback assign-ingredient-to-dispenser(Pod, Dispenser, string/* ingredient-id */);
    callback boost-active-recipe(int/* boost */);
}
