import {
    LogEntry,
    Pod,
    RecipeView,
    Dispenser,
    ConnectionState,
    DispenserType,
    Page,
} from "./../data.slint";
export global StationStateContext {
    out property <string> station-name: "Sir Mix-A-Lot";
    in-out property <bool> station-ready: false;
    out property <Page> active-screen: Page.admin-area-page;
    in-out property <[LogEntry]> log-entries: [];

    callback highlight-dispenser(Pod, Dispenser);
    callback navigated-to(Page, Page);

    public function navigate-to(screen: Page) {
        navigated-to(active-screen, screen);
        active-screen = screen;
    }

    in-out property <[Pod]> pods: /* example data */[
        {
            id: "Pod-Connected",
            connection_state: ConnectionState.connected,
            dispensers:[
                { id: 1, type: DispenserType.pump },
                { id: 2, type: DispenserType.pump },
                { id: 3, type: DispenserType.pump },
                { id: 4, type: DispenserType.pump },
                { id: 5, type: DispenserType.valve },
            ]
        },
        { id: "Pod-Connecting", connection_state: ConnectionState.connecting },
        { id: "Pod-Disconnected", connection_state: ConnectionState.disconnected },
    ];
}
