
import { Palette } from "../palette.slint";
import { RecipeView, CommandStatus } from "../data.slint";
import { ProgressIndicator, Spinner } from "std-widgets.slint";
import { SeperatorText, CommandItem } from "../components.slint";


export component MixProgressPage inherits Rectangle {
    in property <RecipeView> recipe;

    background: Palette.background-elevated;
    GridLayout {
        VerticalLayout {
            width: 33%;
            alignment: start;
            align-items: center;
            padding: 20px;
            padding-top: 40px;
            spacing: 60px;
            rowspan: 1;

            VerticalLayout {
                alignment: start;
                align-items: center;
                spacing: 10px;
                Text {
                    text: "NOW CRAFTING";
                    letter-spacing: 2pt;
                    color: Palette.text-secondary;
                    font-size: 12pt;
                }

                Text {
                    text: recipe.name;
                    color: Palette.text-primary;
                    font-size: 40pt;
                    font-weight: FontWeight.bold;
                }
            }

            VerticalLayout {
                spacing: 10px;
                ProgressIndicator {
                    indeterminate: true;
                    height: 2px;
                    width: 90%;
                }

                Text {
                    text: "analyzing recipe...";
                    letter-spacing: 2pt;
                    color: Palette.text-muted;
                    font-size: 8pt;
                }
            }
        }

        Rectangle {
            width: 1px;
            height: 100%;
            background: Palette.border;
        }

        VerticalLayout {
            padding: 40px;
            spacing: 15px;
            alignment: LayoutAlignment.start;
            rowspan: 2;

            SeperatorText {
                text: "INGREDIENT QUEUE:";
            }

            VerticalLayout {
                spacing: 10px;

                for command in recipe.commands: CommandItem {
                    command: command;
                }
            }
        }
    }
}
