import { ScrollView, HorizontalBox, Slider } from "std-widgets.slint";
import { RecipeView } from "../data.slint";
import { Palette } from "../palette.slint";
import {
    CommandListItem,
    Button,
    SeparatorText,
    LargeText,
    MediumText,
    SmallText,
} from "../components.slint";
import { RecipeContext } from "../globals/recipe-context.slint";
import { ProcessContext } from "../globals/process-context.slint";
import { Page } from "page.slint";

export component RecipeDetailPage inherits Page {
    private property <RecipeView> recipe: RecipeContext.active-recipe;
    callback process-recipe();

    sidebar := VerticalLayout {
        x: 0;
        y: 0;
        width: 33%;
        padding: 20px;
        padding-bottom: 60px;
        spacing: 60px;
        cross-axis-alignment: center;
        alignment: end;
        opacity: root.mounted ? 1 : 0;
        animate opacity {
            duration: Palette.mount-animation-duration;
            easing: Palette.mount-animation-easing;
        }
        Image {
            source: recipe.image;
        }

        Rectangle {
            width: 90%;
            background: Palette.border;
            height: 1px;
        }

        VerticalLayout {
            spacing: 10px;
            cross-axis-alignment: center;
            alignment: center;
            LargeText {
                text: recipe.name;
                primary: true;
            }

            SmallText {
                text: recipe.tag-line[0];
                highlight: true;
            }
        }
    }

    split := Rectangle {
        width: 1px;
        height: 100%;
        x: sidebar.width;
        y: 0;
        background: Palette.border;
    }

    content := VerticalLayout {
        x: split.x + split.width;
        y: 0;
        width: root.width - sidebar.width - split.width;
        padding: 20px;
        padding-top: 40px;
        padding-bottom: 60px;
        spacing: 15px;
        alignment: LayoutAlignment.space-between;
        opacity: root.mounted ? 1 : 0;
        animate opacity {
            duration: Palette.mount-animation-duration;
            easing: Palette.mount-animation-easing;
        }

        VerticalLayout {
            spacing: content.spacing;
            MediumText {
                text: recipe.description;
                color: Palette.text-muted;
                wrap: word-wrap;
            }

            Rectangle { }

            SeparatorText {
                text: "ZUTATEN:";
            }

            GridLayout {
                spacing: 10px;
                for command[index] in recipe.commands: CommandListItem {
                    row: index / 2;
                    col: Math.mod(index, 2);
                    command: command;
                }
            }

            SeparatorText {
                text: "ALKOHOL BOOST:";
            }

            MediumText {
                text: "💪 Alkoholgehalt boosten";
                primary: true;
            }

            HorizontalBox {
                cross-axis-alignment: center;
                SmallText {
                    text: "milde";
                    color: Palette.boost-negative-text;
                }

                booster := Slider {
                    minimum: -50;
                    maximum: 50;
                    value: 0;

                    changed(value) => {
                        RecipeContext.boost-active-recipe(value)
                    }
                }

                SmallText {
                    text: "stark";
                    color: Palette.boost-positive-text;
                }
            }
        }

        Button {
            text: "Zubereiten →";
            clicked => {
                ProcessContext.process-active-recipe(booster.value);
                root.process-recipe();
            }
        }
    }
}
