import { ScrollView } from "std-widgets.slint";
import { RecipeView } from "../data.slint";
import { RecipeCard } from "../components.slint";
import { StationStateContext } from "../globals/station-state-context.slint";
export component RecipeListPage inherits Rectangle {
    callback recipe-selected(RecipeView);

    ScrollView {
        horizontal-scrollbar-policy: ScrollBarPolicy.always-off;

        GridLayout {
            padding: 10px;
            spacing: 5px;
            for recipe[index] in StationStateContext.recipes: RecipeCard {
                row: index / 3;
                col: Math.mod(index, 3);
                recipe: recipe;
                clicked => {
                    root.recipe-selected(recipe)
                }
            }
        }
    }
}
