import { LogEntry, Pod, Dispenser } from "./data.slint";
import { TabWidget } from "std-widgets.slint";
import { PodConfigTab } from "./admin/pod-config-tab.slint";
import { SystemLog } from "components.slint";
import { StationStateContext } from "./globals/station-state-context.slint";

export component AdminArea {
    TabWidget {
        Tab {
            title: "Pod config";
            pod-config := PodConfigTab { }
        }

        Tab {
            title: "System logs";
            SystemLog {
                log-entries: StationStateContext.log-entries;
            }
        }
    }
}
