import { LogEntry, Pod, Dispenser } from "./data.slint";
import { TabWidget } from "std-widgets.slint";
import { PodConfigTab } from "./admin/pod-config-tab.slint";
import { SystemLog } from "components.slint";

export component AdminArea {
    in property <[Pod]> pods;
    in property <[LogEntry]> log-entries;

    callback identify-dispenser <=> pod-config.identify-dispenser;
    callback assign-ingredient-to-dispenser <=> pod-config.assign-ingredient;

    TabWidget {
        Tab {
            title: "Pod config";
            pod-config := PodConfigTab {
                pods: pods;
            }
        }

        Tab {
            title: "System logs";
            SystemLog {
                log-entries: log-entries;
            }
        }
    }
}
