import { LogEntry } from "./data.slint";
import { TabWidget } from "std-widgets.slint";
import { PodConfigTab } from "./admin/pod-config-tab.slint";
import { SystemLog } from "components.slint";

export component AdminArea {
    in property <[LogEntry]> log-entries;

    TabWidget {
        Tab {
            title: "Pod config";
            PodConfigTab { }
        }

        Tab {
            title: "System logs";
            SystemLog {
                log-entries: log-entries;
            }
        }
    }
}
