export { StationStateContext }from "./globals/station-state-context.slint";
export {
    DispenserCalibrationContext,
}from "./globals/dispenser-calibration-context.slint";

import {
    VerticalBox,
    ScrollView,
    HorizontalBox,
    Slider,
} from "std-widgets.slint";
import { Palette } from "palette.slint";
import {
    Page,
    RecipeView,
    Command,
    CommandStatus,
    LogEntry,
    Pod,
    Dispenser,
} from "data.slint";
import { Button } from "components.slint";
import {
    RecipeDetailPage,
    RecipeListPage,
    MixProgressPage,
    BootScreen,
} from "pages.slint";
import { ManualCommandPopup } from "popups.slint";
import { AdminArea } from "admin-area.slint";
import { StationStateContext } from "./globals/station-state-context.slint";

export component AppWindow inherits Window {
    private property <bool> device_ready: StationStateContext.station-ready;
    private property <bool> boot_screen_confirmed: false;
    changed device_ready => {
        if (!device_ready) {
            boot_screen_confirmed = false;
        }
    }
    in property <[string]> ingredient-ids;
    in property <[Pod]> pods;
    in-out property <Page> current_page: Page.admin-area-page;
    in property <[RecipeView]> recipes;
    in-out property <RecipeView> selected_recipe;
    private property <Command> popup_command;

    callback operation_canceled();
    callback boost-recipe(int);
    callback create_recipe(RecipeView, int);
    callback manual-command-confirmed();

    callback identify-dispenser(Pod, Dispenser);
    callback assign-ingredient-to-dispenser(Pod, Dispenser, string);

    public function open-manual-command-popup(command: Command) {
        root.popup_command = command;
        popup.show();
    }
    public function close-manual-command-popup() {
        popup.close();
    }

    operation_canceled => {
        current_page = Page.cocktail-list-page;
    }

    popup := ManualCommandPopup {
        width: root.width;
        height: root.height;
        command: root.popup_command;
        confirmed => {
            root.manual-command-confirmed();
        }
    }

    preferred-width: 1280px;
    preferred-height: 720px;
    background: Palette.background;
    if !device_ready || !boot_screen_confirmed: BootScreen {
        is-loading: !device_ready;
        boot-complete => {
            root.boot_screen_confirmed = true;
        }
    }
    if device_ready && boot_screen_confirmed: VerticalLayout {
        Rectangle {
            height: 50px;
            Button {
                secondary: true;
                text: "← Back";
                x: 20px;
                visible: current_page != Page.cocktail-list-page && current_page != Page.finished-page;
                clicked => {
                    operation_canceled();
                }
            }

            Text {
                text: "Sir Mix-A-Lot";
                font-size: 20pt;
                font-weight: FontWeight.extra-bold;
                letter-spacing: 0.38rem;
                color: Palette.text-secondary;

                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
            }
        }

        Rectangle {
            height: 1px;
            background: Palette.border;
        }

        if current_page == Page.cocktail-list-page: RecipeListPage {
            recipes: recipes;
            recipe-selected(cocktail) => {
                root.selected_recipe = cocktail;
                root.current_page = Page.cocktail-detail-page;
            }
        }

        if current_page == Page.cocktail-detail-page: RecipeDetailPage {
            recipe: root.selected_recipe;
            boost-recipe(boost) => boost-recipe(boost);
            create-recipe(boost) => {
                create_recipe(root.selected_recipe, boost);
                root.current_page = Page.mix-page;
            }
        }

        if current_page == Page.mix-page: MixProgressPage {
            recipe: root.selected_recipe;
        }

        if current_page == Page.admin-area-page: admin-area := AdminArea {
            ingredient-ids: ingredient-ids;
            pods: pods;
            assign-ingredient-to-dispenser(pod, dispenser, ingredient_id) => {
                root.assign-ingredient-to-dispenser(pod, dispenser, ingredient_id);
            };
            identify-dispenser(pod, dispenser) => {
                root.identify-dispenser(pod, dispenser);
            }
        }
    }
}
