
export enum Page { cocktail_list_page, cocktail_detail_page, mix_page, finished_page  }

export enum CommandStatus {
    not_started, in_progress, finished,
}

export enum CommandType {
    dispense, manual
}

export struct Command {
    type: CommandType,
    status: CommandStatus,
    text: string,
    value: string,
}

export struct RecipeView {
    name: string,
    tag_line: [string],
    description: string,
    image: image,
    commands: [Command],
}
