export enum LogLevel {
    trace,
    debug,
    info,
    warn,
    err,
    critical,
}
export struct LogEntry {
    time_stamp: string,
    level: LogLevel,
    message: string,
}

export enum Page {
    cocktail_list_page,
    cocktail_detail_page,
    mix_page,
    finished_page,
    boot_screen,
    admin_area_page,
}

export enum CommandStatus {
    not_started,
    in_progress,
    finished,
}
export struct Command {
    id: int,
    status: CommandStatus,
    text: string,
    value: string,
}

export struct RecipeView {
    id: int,
    name: string,
    tag_line: [string],
    description: string,
    image: image,
    commands: [Command],
}
