import { Palette, Layout } from "../palette.slint";

export component Button {
    in property <string> text;
    in property <bool> secondary;
    in property <bool> enabled <=> i-touch-area.enabled;
    out property <bool> pressed: self.enabled && i-touch-area.pressed;

    callback clicked;

    private property <brush> text-color: self.secondary ? Palette.text-secondary : Palette.text-on-accent;

    min-width: max(32px, i-layout.min-width);
    min-height: max(Layout.touch-height, i-layout.min-height);
    horizontal-stretch: 0;
    vertical-stretch: 0;
    forward-focus: i-focus-scope;

    accessible-role: button;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-action-default => { i-touch-area.clicked(); }

    states [
        disabled when !root.enabled : {
            i-background.background: root.secondary ? Palette.background : Palette.accent-dim;
            i-border.border-color: Palette.border-subtle;
            root.text-color: Palette.text-on-accent;
        }
        pressed when root.pressed : {
            i-background.background: Palette.accent;
            i-border.border-color: Palette.border-strong;
            root.text-color: Palette.text-on-accent;
        }
        hover when i-touch-area.has-hover : {
            i-background.background: Palette.accent-light;
            root.text-color: Palette.text-on-accent;
        }
    ]

    i-background := Rectangle {
        border-radius: 0px;
        background: root.secondary ? Palette.background : Palette.accent;

        animate background, border-color { duration: 150ms; }

        i-border := Rectangle {
            border-radius: parent.border-radius;
            border-width: 1px;
            border-color: Palette.border;
        }

        i-layout := HorizontalLayout {
            padding-left: Layout.spacing-md;
            padding-right: Layout.spacing-md;
            padding-top: Layout.spacing-xs;
            padding-bottom: Layout.spacing-xs;
            spacing: Layout.spacing-xs;
            alignment: center;

            if (root.text != ""): Text {
                font-size: Layout.font-size-sm;
                font-weight: FontWeight.normal;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: root.text;
                color: root.text-color;
                animate color { duration: 150ms; }
                accessible-role: none;
            }
        }
    }

    i-touch-area := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                i-touch-area.clicked();
                 return accept;
            }

            return reject;
        }
    }
}
