import { Palette } from "../palette.slint";
import { Command } from "../data.slint";

export component CommandListItem {
    in property <Command> command;
    VerticalLayout {
        spacing: 10px;
        HorizontalLayout {
            alignment: LayoutAlignment.space-between;
            Text {
                font-size: 10pt;
                text: command.text;
                color: Palette.text-primary;
            }

            Text {
                font-size: 10pt;
                text: command.value;
                color: Palette.text-secondary;
            }
        }

        Rectangle {
            height: 1px;
            background: Palette.border-subtle;
        }
    }
}
