import { Layout } from "../palette.slint";
import { SmallText } from "./small-text.slint";
export component RecipeTags inherits HorizontalLayout {
    in property <[string]> tags;
    padding-top: Layout.spacing-sm;
    alignment: LayoutAlignment.start;
    for t[i] in tags: SmallText {
        text: t + ((i < (tags.length - 1)) ? " | " : "");
        highlight: true;
        horizontal-alignment: left;
        wrap: TextWrap.no-wrap;
        overflow: ((i < (tags.length - 1)) ? TextOverflow.clip : elide);
    }
}
