
import { Palette } from "../palette.slint";
import { RecipeView } from "../data.slint";
import { MediumText } from "./medium-text.slint";
import { RecipeTags } from "./recipe-tags.slint";
export component RecipeCard inherits Rectangle {
    in property <RecipeView> recipe: {
        name: "ExampleName",
        tag_line: ["CLASSIC", "ANTIALKOHOLISCH", "TESTTESTETST"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nisi elit, bibendum vitae mi nec, sodales vulputate felis. Etiam maximus ligula non neque porttitor tincidunt."
    };
    callback clicked();
    border-color: Palette.border;
    border-width: 2px;
    background: Palette.background-card;
    animate background { duration: 200ms; }

    preferred-width: 250px;
    height: self.width;

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked();
        }
    }

    Image {
        source: recipe.image;
        width: parent.width;
        height: parent.height;
    }

    VerticalLayout {

        Rectangle {
            vertical-stretch: 3;
        }

        Rectangle {
            border-color: Palette.border;
            border-width: 2px;
            background: Palette.background-elevated;

            VerticalLayout {
                padding: 20px;
                MediumText {
                    font-size: 20pt;
                    font-weight: FontWeight.bold;
                    text: recipe.name;
                    primary: true;
                }

                RecipeTags {
                    tags: recipe.tag-line;
                }
            }
        }
    }

    states [
        inactive when !ta.has-hover: {}
        active-hover when ta.has-hover: {
            root.background: @radial-gradient(circle, Palette.accent 0%, Palette.background-card 90%);
        }
    ]
}
