import { Palette } from "../palette.slint";
import { SmallText } from "./small-text.slint";
export component SeperatorText {
    in property <string> text;
    HorizontalLayout {
        spacing: 20px;
        align-items: center;

        SmallText {
            text: root.text;
            color: Palette.text-secondary;
        }

        Rectangle {
            height: 1px;
            background: Palette.border;
        }
    }
}
