import { LogEntry, LogLevel } from "../data.slint";
import { Palette } from "../palette.slint";
import { SmallText } from "./small-text.slint";

component Separator inherits SmallText {
    text: "│";
    font-size: 18pt;
    letter-spacing: 0px;
    color: Palette.border;
    vertical-alignment: center;
    horizontal-stretch: 0;
}

component LogRow inherits Rectangle {
    in property <LogEntry> entry;
    background: transparent;

    Rectangle {
        y: parent.height - 1px;
        height: 1px;
        background: Palette.border-subtle;
    }

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        padding-left: 20px;
        padding-right: 20px;
        spacing: 0;
        SmallText {
            text: root.entry.time-stamp;
            letter-spacing: 0.8px;
            vertical-alignment: center;
        }

        Separator { }

        SmallText {
            width: 44px;
            horizontal-stretch: 0;
            text: root.entry.level == LogLevel.trace ? "TRACE"
                : root.entry.level == LogLevel.debug ? "DEBUG"
                : root.entry.level == LogLevel.info ? "INFO"
                : root.entry.level == LogLevel.warn ? "WARN"
                : root.entry.level == LogLevel.err ? "ERROR"
                : root.entry.level == LogLevel.critical ? "CRIT"
                : "INFO";
            letter-spacing: 1.5px;
            vertical-alignment: center;
            color: root.entry.level == LogLevel.trace ? Palette.log-trace
                : root.entry.level == LogLevel.debug ? Palette.log-debug
                : root.entry.level == LogLevel.info ? Palette.log-info
                : root.entry.level == LogLevel.warn ? Palette.log-warn
                : root.entry.level == LogLevel.err ? Palette.log-error
                : root.entry.level == LogLevel.critical ? Palette.log-critical
                : Palette.log-info;
        }

        Separator { }

        SmallText {
            text: root.entry.component;
            letter-spacing: 0.8px;
            vertical-alignment: center;
            overflow: clip;
        }

        Separator { }

        Rectangle {
            width: 12px;
            horizontal-stretch: 0;
            background: transparent;
        }

        SmallText {
            text: root.entry.message;
            letter-spacing: 0.8px;
            vertical-alignment: center;
            overflow: elide;
            color: root.entry.level == LogLevel.err || root.entry.level == LogLevel.critical ? Palette.boost-positive-text
                : Palette.text-primary;
        }
    }
}

export component SystemLog inherits Flickable {
    in property <[LogEntry]> log-entries: [
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.trace,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        },
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.debug,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        },
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.info,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        },
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.warn,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        },
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.err,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        },
        {
            time_stamp: "2025-07-10 10:10:10.00000",
            level: LogLevel.critical,
            component: "some-longer-component",
            message:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
        }
    ];

    viewport-height: log-content.preferred-height;

    log-content := VerticalLayout {
        padding-top: 8px;
        padding-bottom: 8px;
        alignment: start;

        for entry in root.log-entries: LogRow {
            entry: entry;
        }
    }
}
