name: Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Concurrency group to cancel outdated CI runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: Build & Test (Clang 22 / libc++)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          # Required by GetGitRevisionDescription CMake module
          fetch-depth: 0

      - name: Install System Dependencies & LLVM 22
        run: |
          sudo apt-get update
          # Install dependencies
          sudo apt-get install -y libudev-dev libx11-xcb-dev libwayland-dev

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~4.3.0" # cmake 4.4.0 has issues with modules


      - name: Run CMake Workflow
        run: cmake --workflow --preset ci-linux
